### ISSUE TITLE
Adding onto the README

### ISSUE THREAD

**Issue by Kingpin1111** [ubccapico/node-canvas-api#7]
Hi Justin!

I had a look at your canvas API for node and tried playing around with it. It's amazing! I wanted to create extensions to this, but am not entirely sure what to do for a few things. Would you perhaps have the answer to these questions?

- Is ' npm run build:cjs ' the command to build the files? (I want to run some of the example methods you created in the src/source files, but am not able to).

- In the README, it is asked to create my contributions in the source directory. I'm trying to run the example usage you have provided in the README in the src folder (with the command 'node index.js' on the terminal) and it is telling me that getSelf() is not defined, yet I believe it is being imported within the same folder. Could you perhaps walk me along the steps to build and test this application so I can add onto the documentation you have in the README?

**Comment by justin0022** [comment]
No problem, I’m happy to help.
 
To build the files (which takes the files in the `source` folder and outputs them to `src`), `npm run build` will work, which is equivalent to `npm run build:cjs`.
 
To run the example usage, create an `index.js` file in the root of the project, and then copy/paste the sample code into `index.js`:
```js
const getSelf = require('./src/getSelf')
getSelf().then(x => console.log(x))
 ```
 
Then you should be able to run `node index.js` to execute the `getSelf` function.
 
The process for making new additions are:
1. Add new file to `source` folder (say that the new file you want to add is ‘getUsersWithGradeThreshold.js`)
1. In the `source` folder, there’s an `index.js` file that lists all of the files you want exported to `src`. There you will add: `export { default as getUsersWithGradeThreshold } from './getUsersWithGradeThreshold'`
1. Run `npm run build`, which will build the project and output your new function into `src`.
1. In the `index.js` at the root of the project that you create (this is not the `index.js` that’s in the `source` folder), import your new file from `src` like this: `const getUsersWithGradeThreshold = require('.src/getUsersWithGradeThreshold')` and test by running the code: `node index.js`.
1. Once you’re happy that it works, create a PR.
 
Please feel free to make improvements to the README – I really appreciate it!
 
The entire process is a little cumbersome – the reason for this is because I wanted the package to be compatible with UMD and CJS and at the time this seemed like the best option. It’s copied from how Ramda had its package set up: https://github.com/ramda/ramda

Hope this helps. If you have any questions or need help let me know.

**Comment by justin0022** [comment]
@Kingpin1111  just wanted to follow up to see if I can close this issue now.
